In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_socioeconomic_data_df = pd.read_csv("./data/CA_modified_data_for_socioeconomic_data.csv")
raw_socioeconomic_data_df

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Total,Total,OVR,OVERALL
1,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Male,GEN,MALE
2,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Female,GEN,FEMALE
3,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,Less than high school,EDU,EDUHS
4,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,High school graduate,EDU,EDUHSGRAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53387,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Asian,RACE,RACEASN
53388,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI
53389,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA
53390,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,2 or more races,RACE,RACE2PLUS
53391,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Other,RACE,RACEOTH

In [3]:
california_data = raw_socioeconomic_data_df.loc[((raw_socioeconomic_data_df["LocationDesc"] == "California") 
                                                 & (raw_socioeconomic_data_df["Class"] == "Obesity / Weight Status"))]
california_data = california_data.rename({"LocationAbbr":"State (Abbreviation)",
                        "LocationDesc":"State",
                        "Datasource":"Source",
                        "Question":"Have Obesity/Overweight Classification",
                        "Data_Value":"Obesity Percentage",
                        "Sample_Size":"Number of Samples",
                        "Education":"Level of Education"
                       }, axis='columns')

california_data.loc[("have obesity" in string for string in california_data["Have Obesity/Overweight Classification"].astype("string")), "Have Obesity/Overweight Classification"] = "obesity"

california_data

,YearStart,YearEnd,State (Abbreviation),State,Source,Class,Topic,Have Obesity/Overweight Classification,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
2568,2011,2011,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Age (years),55 - 64,AGEYR,AGEYR5564
2674,2012,2012,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Total,Total,OVR,OVERALL
2676,2012,2012,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Gender,Female,GEN,FEMALE
2701,2011,2011,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Total,Total,OVR,OVERALL
2702,2011,2011,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Gender,Male,GEN,MALE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50524,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Race/Ethnicity,Asian,RACE,RACEASN
50525,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI
50526,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA
50527,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Race/Ethnicity,2 or more races,RACE,RACE2PLUS
50528,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,obesity,NaN,Value,...,"(37.63864012300047, -120.99999953799971)",OWS,OWS1,Q036,VALUE,6,Race/Ethnicity,Other,RACE,RACEOTH

In [4]:
california_data = california_data[["YearStart", "YearEnd", "State", "Class","Have Obesity/Overweight Classification", "Obesity Percentage", "Number of Samples", "Age(years)", "Level of Education", "Gender", "Income", "Race/Ethnicity"]]
california_data

,YearStart,YearEnd,State,Class,Have Obesity/Overweight Classification,Obesity Percentage,Number of Samples,Age(years),Level of Education,Gender,Income,Race/Ethnicity
2568,2011,2011,California,Obesity / Weight Status,obesity,27.6,3520.0,55 - 64,NaN,NaN,NaN,NaN
2674,2012,2012,California,Obesity / Weight Status,obesity,25.0,13646.0,NaN,NaN,NaN,NaN,NaN
2676,2012,2012,California,Obesity / Weight Status,obesity,23.8,7694.0,NaN,NaN,Female,NaN,NaN
2701,2011,2011,California,Obesity / Weight Status,obesity,23.8,17088.0,NaN,NaN,NaN,NaN,NaN
2702,2011,2011,California,Obesity / Weight Status,obesity,23.1,7159.0,NaN,NaN,Male,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
50524,2016,2016,California,Obesity / Weight Status,obesity,9.6,848.0,NaN,NaN,NaN,NaN,Asian
50525,2016,2016,California,Obesity / Weight Status,obesity,NaN,NaN,NaN,NaN,NaN,NaN,Hawaiian/Pacific Islander
50526,2016,2016,California,Obesity / Weight Status,obesity,38.2,74.0,NaN,NaN,NaN,NaN,American Indian/Alaska Native
50527,2016,2016,California,Obesity / Weight Status,obesity,29.4,251.0,NaN,NaN,NaN,NaN,2 or more races
50528,2016,2016,California,Obesity / Weight Status,obesity,28.4,122.0,NaN,NaN,NaN,NaN,Other

In [5]:
age_ranges = california_data["Age(years)"].unique()
print(age_ranges)
education_levels = california_data["Level of Education"].unique()
print(education_levels)
gender = california_data["Gender"].unique()
print(gender)
income_ranges = california_data["Income"].unique()
print(income_ranges)
race_ethnicity = california_data["Race/Ethnicity"].unique()
print(race_ethnicity)

['55 - 64' nan '18 - 24' '25 - 34' '35 - 44' '45 - 54' '65 or older']
[nan 'Less than high school' 'High school graduate'
 'Some college or technical school' 'College graduate']
[nan 'Female' 'Male']
[nan 'Less than $15,000' '$15,000 - $24,999' '$25,000 - $34,999'
 '$35,000 - $49,999' '$50,000 - $74,999' '$75,000 or greater'
 'Data not reported']
[nan 'Non-Hispanic White' 'Non-Hispanic Black' 'Hispanic' 'Asian'
 'Hawaiian/Pacific Islander' 'American Indian/Alaska Native'
 '2 or more races' 'Other']

In [6]:
age_data = california_data.dropna(subset = ["Age(years)"])
age_data = age_data[["YearEnd", "State", "Class", "Have Obesity/Overweight Classification", "Obesity Percentage", "Number of Samples", "Age(years)"]]
age_data.head(20)

,YearEnd,State,Class,Have Obesity/Overweight Classification,Obesity Percentage,Number of Samples,Age(years)
2568,2011,California,Obesity / Weight Status,obesity,27.6,3520.0,55 - 64
2708,2011,California,Obesity / Weight Status,obesity,14.5,902.0,18 - 24
2709,2011,California,Obesity / Weight Status,obesity,23.7,1826.0,25 - 34
2710,2011,California,Obesity / Weight Status,obesity,25.9,2578.0,35 - 44
2711,2011,California,Obesity / Weight Status,obesity,27.6,2969.0,45 - 54
2712,2011,California,Obesity / Weight Status,obesity,21.2,5293.0,65 or older
2734,2011,California,Obesity / Weight Status,overweight,26.8,902.0,18 - 24
2735,2011,California,Obesity / Weight Status,overweight,36.1,1826.0,25 - 34
2736,2011,California,Obesity / Weight Status,overweight,38.1,2577.0,35 - 44
2737,2011,California,Obesity / Weight Status,overweight,39.0,2969.0,45 - 54
2738,2011,California,Obesity / Weight Status,overweight,38.1,3519.0,55 - 64
2739,2011,California,Obesity / Weight Status,overweight,38.2,5293.0,65 or older
2959,2012,California,Obesity / Weight Status,obesity,12.2,855.0,18 - 24
2960,2012,California,Obesity / Weight Status,obesity,23.2,1700.0,25 - 34
2961,2012,California,Obesity / Weight Status,obesity,28.7,1999.0,35 - 44
2962,2012,California,Obesity / Weight Status,obesity,31.3,2328.0,45 - 54
2963,2012,California,Obesity / Weight Status,obesity,30.6,2667.0,55 - 64
2964,2012,California,Obesity / Weight Status,obesity,21.1,4092.0,65 or older
2986,2012,California,Obesity / Weight Status,overweight,22.8,855.0,18 - 24
2987,2012,California,Obesity / Weight Status,overweight,36.4,1700.0,25 - 34

In [7]:
level_of_education_data = california_data.dropna(subset = ["Level of Education"])
level_of_education_data = level_of_education_data[["YearEnd", "State", "Class","Have Obesity/Overweight Classification", "Obesity Percentage", "Number of Samples", "Level of Education"]]
level_of_education_data.head(20)

,YearEnd,State,Class,Have Obesity/Overweight Classification,Obesity Percentage,Number of Samples,Level of Education
2704,2011,California,Obesity / Weight Status,obesity,32.9,1870.0,Less than high school
2705,2011,California,Obesity / Weight Status,obesity,26.4,3146.0,High school graduate
2706,2011,California,Obesity / Weight Status,obesity,24.0,5375.0,Some college or technical school
2707,2011,California,Obesity / Weight Status,obesity,15.3,6681.0,College graduate
2730,2011,California,Obesity / Weight Status,overweight,40.3,1870.0,Less than high school
2731,2011,California,Obesity / Weight Status,overweight,37.0,3146.0,High school graduate
2732,2011,California,Obesity / Weight Status,overweight,34.5,5375.0,Some college or technical school
2733,2011,California,Obesity / Weight Status,overweight,35.6,6681.0,College graduate
2955,2012,California,Obesity / Weight Status,obesity,34.8,1578.0,Less than high school
2956,2012,California,Obesity / Weight Status,obesity,26.4,2568.0,High school graduate
2957,2012,California,Obesity / Weight Status,obesity,26.3,3620.0,Some college or technical school
2958,2012,California,Obesity / Weight Status,obesity,16.0,5869.0,College graduate
2982,2012,California,Obesity / Weight Status,overweight,37.8,1578.0,Less than high school
2983,2012,California,Obesity / Weight Status,overweight,36.2,2568.0,High school graduate
2984,2012,California,Obesity / Weight Status,overweight,34.3,3620.0,Some college or technical school
2985,2012,California,Obesity / Weight Status,overweight,34.2,5869.0,College graduate
3036,2013,California,Obesity / Weight Status,obesity,34.3,1258.0,Less than high school
3037,2013,California,Obesity / Weight Status,obesity,24.5,2142.0,High school graduate
3038,2013,California,Obesity / Weight Status,obesity,26.4,2872.0,Some college or technical school
3039,2013,California,Obesity / Weight Status,obesity,14.3,4382.0,College graduate

In [8]:
gender_data = california_data.dropna(subset = ["Gender"])
gender_data = gender_data[["YearEnd", "State", "Class","Have Obesity/Overweight Classification", "Obesity Percentage", "Number of Samples", "Gender"]]
gender_data.head(20)

,YearEnd,State,Class,Have Obesity/Overweight Classification,Obesity Percentage,Number of Samples,Gender
2676,2012,California,Obesity / Weight Status,obesity,23.8,7694.0,Female
2702,2011,California,Obesity / Weight Status,obesity,23.1,7159.0,Male
2703,2011,California,Obesity / Weight Status,obesity,24.5,9929.0,Female
2728,2011,California,Obesity / Weight Status,overweight,44.1,7159.0,Male
2729,2011,California,Obesity / Weight Status,overweight,28.5,9929.0,Female
2954,2012,California,Obesity / Weight Status,obesity,26.2,5952.0,Male
2980,2012,California,Obesity / Weight Status,overweight,40.8,5952.0,Male
2981,2012,California,Obesity / Weight Status,overweight,29.8,7694.0,Female
3034,2013,California,Obesity / Weight Status,obesity,25.1,4828.0,Male
3035,2013,California,Obesity / Weight Status,obesity,23.1,5841.0,Female
3062,2013,California,Obesity / Weight Status,overweight,42.2,4828.0,Male
3063,2013,California,Obesity / Weight Status,overweight,29.7,5841.0,Female
3289,2014,California,Obesity / Weight Status,obesity,24.0,3932.0,Male
3290,2014,California,Obesity / Weight Status,obesity,25.4,4093.0,Female
3317,2014,California,Obesity / Weight Status,overweight,42.2,3932.0,Male
3318,2014,California,Obesity / Weight Status,overweight,27.6,4093.0,Female
45995,2015,California,Obesity / Weight Status,obesity,23.7,5718.0,Female
45996,2015,California,Obesity / Weight Status,obesity,24.6,5741.0,Male
46023,2015,California,Obesity / Weight Status,overweight,30.2,5718.0,Female
46024,2015,California,Obesity / Weight Status,overweight,41.8,5741.0,Male

In [9]:
income_data = california_data.dropna(subset = ["Income"])
income_data = income_data[["YearEnd", "State", "Class","Have Obesity/Overweight Classification", "Obesity Percentage", "Number of Samples", "Income"]]
income_data = income_data.loc[income_data["Income"] != "Data not reported"]
income_data.head(20)

,YearEnd,State,Class,Have Obesity/Overweight Classification,Obesity Percentage,Number of Samples,Income
2713,2011,California,Obesity / Weight Status,obesity,29.9,2589.0,"Less than $15,000"
2714,2011,California,Obesity / Weight Status,obesity,30.1,2203.0,"$15,000 - $24,999"
2715,2011,California,Obesity / Weight Status,obesity,27.2,1622.0,"$25,000 - $34,999"
2716,2011,California,Obesity / Weight Status,obesity,22.1,1915.0,"$35,000 - $49,999"
2717,2011,California,Obesity / Weight Status,obesity,24.3,2263.0,"$50,000 - $74,999"
2718,2011,California,Obesity / Weight Status,obesity,17.7,5406.0,"$75,000 or greater"
2740,2011,California,Obesity / Weight Status,overweight,35.2,2589.0,"Less than $15,000"
2741,2011,California,Obesity / Weight Status,overweight,35.7,2203.0,"$15,000 - $24,999"
2742,2011,California,Obesity / Weight Status,overweight,34.8,1622.0,"$25,000 - $34,999"
2743,2011,California,Obesity / Weight Status,overweight,38.4,1915.0,"$35,000 - $49,999"
2744,2011,California,Obesity / Weight Status,overweight,36.5,2263.0,"$50,000 - $74,999"
2745,2011,California,Obesity / Weight Status,overweight,38.2,5406.0,"$75,000 or greater"
2965,2012,California,Obesity / Weight Status,obesity,29.9,2152.0,"Less than $15,000"
2966,2012,California,Obesity / Weight Status,obesity,30.2,1699.0,"$15,000 - $24,999"
2967,2012,California,Obesity / Weight Status,obesity,28.7,1194.0,"$25,000 - $34,999"
2968,2012,California,Obesity / Weight Status,obesity,23.4,1559.0,"$35,000 - $49,999"
2969,2012,California,Obesity / Weight Status,obesity,27.0,1879.0,"$50,000 - $74,999"
2970,2012,California,Obesity / Weight Status,obesity,20.1,4280.0,"$75,000 or greater"
2992,2012,California,Obesity / Weight Status,overweight,31.2,2152.0,"Less than $15,000"
2993,2012,California,Obesity / Weight Status,overweight,34.6,1699.0,"$15,000 - $24,999"

In [10]:
race_ethnicity_data = california_data.dropna(subset = ["Race/Ethnicity"])
race_ethnicity_data = race_ethnicity_data[["YearEnd", "State", "Class","Have Obesity/Overweight Classification", "Obesity Percentage", "Number of Samples", "Race/Ethnicity"]]
race_ethnicity_data = race_ethnicity_data.dropna()
race_ethnicity_data.head(20)

,YearEnd,State,Class,Have Obesity/Overweight Classification,Obesity Percentage,Number of Samples,Race/Ethnicity
2720,2011,California,Obesity / Weight Status,obesity,22.0,10988.0,Non-Hispanic White
2721,2011,California,Obesity / Weight Status,obesity,33.1,652.0,Non-Hispanic Black
2722,2011,California,Obesity / Weight Status,obesity,30.3,3923.0,Hispanic
2723,2011,California,Obesity / Weight Status,obesity,8.1,889.0,Asian
2724,2011,California,Obesity / Weight Status,obesity,23.2,85.0,Hawaiian/Pacific Islander
2725,2011,California,Obesity / Weight Status,obesity,37.3,151.0,American Indian/Alaska Native
2726,2011,California,Obesity / Weight Status,obesity,26.9,315.0,2 or more races
2747,2011,California,Obesity / Weight Status,overweight,36.2,10988.0,Non-Hispanic White
2748,2011,California,Obesity / Weight Status,overweight,38.9,652.0,Non-Hispanic Black
2749,2011,California,Obesity / Weight Status,overweight,39.8,3923.0,Hispanic
2751,2011,California,Obesity / Weight Status,overweight,29.7,889.0,Asian
2752,2011,California,Obesity / Weight Status,overweight,26.2,85.0,Hawaiian/Pacific Islander
2753,2011,California,Obesity / Weight Status,overweight,31.9,151.0,American Indian/Alaska Native
2754,2011,California,Obesity / Weight Status,overweight,30.0,315.0,2 or more races
2972,2012,California,Obesity / Weight Status,obesity,23.3,8313.0,Non-Hispanic White
2973,2012,California,Obesity / Weight Status,obesity,36.6,622.0,Non-Hispanic Black
2974,2012,California,Obesity / Weight Status,obesity,31.1,3267.0,Hispanic
2975,2012,California,Obesity / Weight Status,obesity,10.3,799.0,Asian
2976,2012,California,Obesity / Weight Status,obesity,31.4,86.0,Hawaiian/Pacific Islander
2977,2012,California,Obesity / Weight Status,obesity,17.6,107.0,American Indian/Alaska Native